services:
  - type: web
    name: dogsoc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: monkey60
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
